remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Contact Card]
description: [Hey, my name is Andre but I go by HydroponicTrash online. Why HydroponicTrash? Because I build indoor vertical gardens from trash and other recycled things. Im a hacker, a gardener, and an overall weirdo. I write alot about solarpunk (links down below to learn more), anarchism, ecosocialism, hacking, permacomputing, and a ton of other topics.]
